[theme]
base="light"
primaryColor="#4B5942"            # heritage green  (maybe 2f4f2f)
backgroundColor="#E8ECD9"         # your screenshot green
secondaryBackgroundColor="#F5F7EE"
textColor="#1F241C"
font="serif"
